<?php //[STAMP] 75e823446a08a51994818e2254b9df0e
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait FunctionalTesterActions {
	/**
	 * @return \Codeception\Scenario
	 */
	abstract protected function getScenario ();

}
