<?php //[STAMP] fb5f849941bea88a7b747cb1594a9bc9
namespace _generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait FunctionalTesterActions {
	/**
	 * @return \Codeception\Scenario
	 */
	abstract protected function getScenario ();

}
